# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('date_register', models.DateField()),
                ('time_contract', models.DateField()),
                ('type_plane', models.CharField(choices=[('Plano', 'Plano'), ('Avulso', 'Avulso')], max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sex', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('dentista_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_clinica.Dentista')),
                ('date_entry', models.DateField()),
                ('function', models.CharField(choices=[('Gerente', 'Gerente'), ('Zelador(a)', 'Zelador(a)'), ('Atendente', 'Atendente'), ('Vigia', 'Vigia'), ('Seguranca', 'Seguranca')], max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('salary', models.FloatField()),
            ],
            bases=('app_clinica.dentista', models.Model),
        ),
        migrations.AddField(
            model_name='cliente',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clinica.Dentista'),
        ),
    ]
